name:                start
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/githubuser/start#readme
license:             BSD3
author:              Author name here
maintainer:          example@example.com
copyright:           2017 Author name here
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - lens
  - mtl
  - exceptions
  - transformers
  - time
  - directory
  - unix
  - managed

executables:
  start:
    source-dirs:      src
    main:             Main.hs
